### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JamesChenTW09**
陳靖
James Chen

http://34.200.206.129:3000/api/attractions?page=0
http://34.200.206.129:3000/api/attractions?page=0&keyword=溫泉
http://34.200.206.129:3000/api/attraction/10

再麻煩老師了，希望一切順利!!

### CODE REVIEW

**Comment by cwpeng** [comment]
Almost done but two issues:

1.
```
#取得資料庫資料總筆數，放進totalId變數裡
cursor.execute("SELECT COUNT(`id`) FROM `attraction`")
totalId = cursor.fetchone()
```
We will get total number of attractions in every request we need it, not only once at server start. Because we assume attractions data may increase or decrease during the lifetime of our website. Don't worry, it's optimized if we use count(id) to get it.

2.
Response of http://34.200.206.129:3000/api/attraction/10 should use "data" field according to API spec.

Fix issues, create new commits, and leave message for me to review again.

**Comment by JamesChenTW09** [comment]
Thanks for the immediate response and feedback
I move count(id) execute into the route, and change "datas" to "data"
Please check again.
Thanks

**Comment by cwpeng** [comment]
Issues fixed. But, please add rule to your `main` branch: at least 1 review approval before merging. You will see the changes in this page after finishing setup it.

**Comment by JamesChenTW09** [comment]
Done!!

**Review by cwpeng — APPROVED** [review]
OK. Good.

**Pull request merged**
